### ISSUE TITLE
[IPFS] IFPS AMI update and running node upgrade

### ISSUE THREAD

**Issue by devformatters** [thematters/matters-docker#22]
### Tasks
- [x] IPNS Feed required specific environment. Thus, need a new AMI for IPFS Node
- [x] Manually update current running nodes (make sure it works normally)
- [x] Make sure [node management script](https://github.com/thematters/serverless-ipfs-node-management/blob/develop/services/base.ts#L403) use the updated AMI

### References
- [Thread](https://mattersnews.slack.com/archives/C88CK7Q7L/p1661959577977399)

### Related Issues
- https://github.com/thematters/matters-ipfs/issues/1
